name = "learn-next15"
type = "javascript"

[build]
command = "npm run build"
upload = { dir = ".next", format = "service-worker" }

compatibility_date = "2024-09-10"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"